### PR TITLE
Updated regex to accept . while filtering name

### PR DESCRIPTION
**Pull request by RakshithBeta**
I have tested the regex for these cases.
| test case | output |
| -------- | ----- | 
| test1.jpeg  | test1.jpeg |
| test2(2).....jpeg | test22.jpeg|
| testFile(1)js | testFile1js | 
| latest.png | latest.png |
| file.123.png | file123.png|

### CODE REVIEW

**Review by rjvim — APPROVED** [review]

**Comment by rjvim** [comment]
@RakshithBeta Approved for now, but PR Description can be better.

Example, I tried `https://github.com/nobejs/files/pull/19.diff`, copied the diff, asked ChatGPT: "Generate summary and what it does for following diff, and few test cases in markdown checklist format."

-------

### Summary of the Diff

This diff updates the function `removeSpecialCharactersFromFileName` in a JavaScript file. The change is specifically in the regular expression `nonAlphanumericRegex`.

- **Before Change:** The regex was `/[^a-zA-Z0-9]/g`, which matches any character that is not an alphanumeric character (i.e., not a-z, A-Z, or 0-9).

- **After Change:** The regex is modified to `/[^a-zA-Z0-9](?=.*\.)/g`. This new regex still matches any non-alphanumeric character, but with an additional lookahead assertion `(?=.*\.)`. This assertion checks if there is a dot (`.`) somewhere ahead in the string. Therefore, the replacement only occurs for non-alphanumeric characters that are followed by a dot somewhere later in the string.

### Purpose of the Change

The change in the regular expression alters the behavior of the `removeSpecialCharactersFromFileName` function. It now removes non-alphanumeric characters only if they are followed by a dot somewhere in the string. This can be particularly useful in file name sanitization where the dot may be used to denote file extensions, and we don't want to remove special characters that are part of the file extension.

### Test Cases

#### Markdown Checklist for Test Cases

- [ ] **Test Case 1:** Input string without any dots.
  - Input: `"example_file@#"`
  - Expected Output: `"example_file@#"` (No change, as there are no dots in the string)

- [ ] **Test Case 2:** Input string with a dot, but no special characters before the dot.
  - Input: `"example.file"`
  - Expected Output: `"example.file"` (No change, as there are no non-alphanumeric characters before the dot)

- [ ] **Test Case 3:** Input string with non-alphanumeric characters before and after a dot.
  - Input: `"ex@#ample.fi!le"`
  - Expected Output: `"example.fi!le"` (Removes non-alphanumeric characters before the dot only)

- [ ] **Test Case 4:** Input string with multiple dots.
  - Input: `"ex@#am.ple.fi!le"`
  - Expected Output: `"exam.ple.fi!le"` (Removes non-alphanumeric characters only before each dot)

- [ ] **Test Case 5:** Input string with non-alphanumeric characters at the end, after a dot.
  - Input: `"example.file@#"`
  - Expected Output: `"example.file@#"` (No change, as the non-alphanumeric characters are after the dot)

These test cases cover various scenarios to ensure the function behaves as expected with different kinds of input strings.

**Comment by rjvim** [comment]
@RakshithBeta In above test cases, just mark them as "done" if already covered.

**Comment by RakshithBeta** [comment]
@rjvim okay will do this

**Comment by RakshithBeta** [comment]
Test Cases
Markdown Checklist for Test Cases

- [x] Test Case 1: Input string without any dots.
        Input: "example_file@#"
        Expected Output: "example_file@#"

- [x] Test Case 2: Input string with a dot, but no special characters before the dot.
         Input: "example.file"
         Expected Output: "example.file"
 

- [x] Test Case 3: Input string with non-alphanumeric characters before and after a dot.
         Input: "ex@#ample.fi!le" 
         Expected Output: "example.fi!le"
 

- [ ] Test Case 4: Input string with multiple dots.
         Input: "ex@#am.ple.fi!le"
         Expected Output: "exam.ple.fi!le" 
         @rjvim Here the output we are getting is example.fi!le is this okay.

- [x] Test Case 5: Input string with non-alphanumeric characters at the end, after a dot.
         Input: "example.file@#"
         Expected Output: "example.file@#"

**Comment by rjvim** [comment]
@RakshithBeta Merged and released: https://github.com/nobejs/files/actions/runs/7990228690

**Pull request merged**
